
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  server:
#    port: 9292
  endpoint:
    health:
      show-details: always
#      show-components: always
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
#    git:
#      mode: full

info:
  app:
    name: hello-actuator
    comapny: songbeom

logging:
  level:
    hello.controller: DEBUG

server:
  tomcat:
    mbeanregistry:
      enabled: true